# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100, verbose_name='Identificacion')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fuerza_publica', models.CharField(max_length=100, verbose_name='Fuerza Publica')),
                ('rango', models.CharField(max_length=100, verbose_name='Rango')),
                ('id_fp', models.CharField(max_length=100, verbose_name='ID Fuerza')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electronico')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
