# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agente',
            old_name='identificacion',
            new_name='identificacion',
        ),
    ]
