# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20171120_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='fuerza_publica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuerza Pública'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='id_fp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Fuerza'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='rango',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rango'),
        ),
    ]
