# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('fecha_expedicion', models.DateTimeField(verbose_name='Fecha de expedicion')),
                ('rh', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=1)),
                ('grupo_sanguineo', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=1)),
                ('estatura', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('requerido', models.BooleanField(default=False)),
                ('lugar_expedicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar_expedicion', to='restapi.Ciudad')),
                ('lugar_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar_nacimiento', to='restapi.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='tipo_identficacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Identificacion'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Departamento'),
        ),
    ]
