# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=9),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='rh',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3),
        ),
    ]
