# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20171012_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudadano',
            old_name='tipo_identficacion',
            new_name='tipo_identificacion',
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='fecha_expedicion',
            field=models.DateField(verbose_name='Fecha de expedicion'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
